### PR TITLE
Mediaflux silently fails to create a project with missing metadata

### LINKED ISSUE #650: When a project is missing metadata, mediaflux silently fails to create it
### Expected behavior
I expect that if I make a project in mediaflux, and that project fails to be created because it is missing required metadata, that there would be a meaningful error telling me what information is missing so I can fix the issue. 

### Actual behavior
Instead, it just silently fails. We can tell the mediaflux asset wasn't created, but we can't easily tell why.

### Steps to replicate
```
(byebug) project = FactoryBot.create(:project)
#<Project id: 1378, mediaflux_id: nil, metadata_json: {"data_sponsor"=>"danuta_carroll", "data_manager"=>"nathanaeljustin", "data_user_read_only"=>[], "data_user_read_write"=>[], "departments"=>["RDSS", "PRDS"], "directory"=>"big-data", "title"=>"The Men from Outer Space", "description"=>"a random description", "created_on"=>"2024-04-19T08:10:56-04:00", "created_by"=>"edison", "updated_on"=>"2024-04-19T08:10:56-04:00", "updated_by"=>"desmond", "project_id"=>nil, "status"=>"pending", "storage_capacity_requested"=>"500 GB", "storage_performance_expectations_requested"=>"standard", "project_purpose"=>"research"}, created_at: "2024-04-19 12:10:56.932476000 +0000", updated_at: "2024-04-19 12:10:56.932476000 +0000">
(byebug) project.mediaflux_id = ProjectMediaflux.create!(project:, session_id: )
"" <-- The mediaflux project wasn't created, but it isn't clear why, we just get a blank id back
(byebug) project.mediaflux_id
nil 
```

Whereas, if we create the `project` object with the required metadata: 
```
(byebug) project = FactoryBot.create(:project, project_id: "doi:123:456", directory: "something")
#<Project id: 1380, mediaflux_id: nil, metadata_json: {"data_sponsor"=>"brian", "data_manager"=>"fritz_erdman", "data_user_read_only"=>[], "data_user_read_write"=>[], "departments"=>["RDSS", "PRDS"], "directory"=>"something", "title"=>"Death Brain", "description"=>"a random description", "created_on"=>"2024-04-19T08:17:46-04:00", "created_by"=>"enoch", "updated_on"=>"2024-04-19T08:17:46-04:00", "updated_by"=>"efren_jerde", "project_id"=>"doi:123:456", "status"=>"pending", "storage_capacity_requested"=>"500 GB", "storage_performance_expectations_requested"=>"standard", "project_purpose"=>"research"}, created_at: "2024-04-19 12:17:46.364057000 +0000", updated_at: "2024-04-19 12:17:46.364057000 +0000">
(byebug) project.mediaflux_id = ProjectMediaflux.create!(project:, session_id: )
"1319" <-- Now mediaflux made an asset and gave us the ID
```

### Impact of this bug
We spend more time than we should figuring out why something wasn't created in mediaflux. As our schema evolves, and as we face the challenge of keeping the schema definition in rails in sync with the schema definition in mediaflux, it's going to become ever more important to detect metadata issues early and clearly. 

### Implementation notes, if any
I'd like to see a custom exception class raised for metadata issues. This would allow us to see them in Honeybadger and know how often they're happening. All exceptions that are raised should include the current expected metadata schema version number, as well as what metadata is missing.

### PR DESCRIPTION
**Pull request by JaymeeH**
testing what error gets returned when we attempt to create a project in mediaflux with missing metadata

closes #650

### CODE REVIEW

**Review by bess — APPROVED** [review]

**Review by hectorcorrea — APPROVED** [review]

File: app/models/project_mediaflux.rb [hunk 1]
```diff
@@ -28,9 +28,24 @@ def self.create!(project:, session_id:, xml_namespace: nil)
...
+      response_xml = create_request.response_xml
+      response_text = response_xml.text
+      case response_text
+      when "failed: The namespace #{project_namespace} already contains an asset named '#{project_name}'"
+        raise "Project name already taken"
+      when /'asset.create' failed/
+
+        # Ensure that the metadata validations are run
+        project.metadata_model.validate
+        raise TigerData::MissingMetadata.missing_metadata(schema_version:"0.6", errors: project.metadata_model.errors)
```
Comment (hectorcorrea) [inline app/models/project_mediaflux.rb:45]: Is this correct? We are issuing `raise` here but `TigerData::MissingMetadata.missing_metadata` also issues a `raise` ... does not quite feels right, am I missing something?

File: app/models/tigerdata_schema.rb [hunk 2]
```diff
@@ -125,6 +125,13 @@ def project_schema_fields
      storage_performance, project_purpose]
   end
   # rubocop:enable Metrics/MethodLength
+  def project_schema_fields
+    self.class.project_schema_fields
+  end
+
+  def self.required_project_schema_fields
+    project_schema_fields.select { |field| field["min-occurs"] > 0 }
```
Comment (hectorcorrea) [inline app/models/tigerdata_schema.rb:133]: cool!

File: app/models/project_mediaflux.rb (hunk 1 above)
Comment (hectorcorrea) [reply app/models/project_mediaflux.rb:45]: I feel like we should just `raise TigerData::MetadataError` here since that class inherits from `StandardError` but maybe I am missing the point of `TigerData::MissingMetadata`

File: app/models/project_metadata.rb [hunk 3]
```diff
@@ -58,17 +74,47 @@ def create( params:)
     project.metadata["project_id"]
   end
 
+  def required_keys
+    tableized = required_field_labels.map { |v| v.parameterize.underscore }
+    tableized.map(&:to_sym)
```
Comment (hectorcorrea) [inline app/models/project_metadata.rb:79]: You probably could avoid the second call to `.map` if you update the first one to do `v.parameterize.underscore.to_sym`. No big deal either way.

File: app/models/project_metadata.rb [hunk 4]
```diff
@@ -58,17 +74,47 @@ def create( params:)
...
+          directory: params[:directory],
+          title: params[:title],
+          description: params[:description],
+          status: params[:status],
+          project_id: project.metadata[:project_id],
+          storage_capacity_requested: project.metadata[:storage_capacity_requested] || Rails.configuration.project_defaults[:storage_capacity_requested],
+          storage_performance_expectations_requested: project.metadata[:storage_performance_expectations_requested] || Rails.configuration.project_defaults[:storage_performance_expectations_requested],
+          project_purpose: project.metadata[:project_purpose] || Rails.configuration.project_defaults[:project_purpose]
+        }
+        #[:codes, :titles, :statuses, :"data sponsors", :"data managers", :"affiliated department(s)s", :"created ons", :"created bies", :"project ids", :"storage capacities", :"storage performance expectations", :"project purposes"]
```
Comment (hectorcorrea) [inline app/models/project_metadata.rb:100]: ???

**Review by hectorcorrea — COMMENTED** [review]
Left a few comments...let me know if you'd rather chat about them

File: app/models/project_mediaflux.rb (hunk 1 above)
Comment (JaymeeH) [reply app/models/project_mediaflux.rb:45]: Thanks for the feedback — So `TigerData::MissingMetadata.missing_metadata ` itself isn't the error, but rather a vehicle to receive and project the prevalent project information within the error e.g the schema version, and fields causing the error. If you think it would be better to try and move this logic into `TigerData::MetadataError` we can talk about it
