### PR TITLE
Simpler architecture proposal

### LINKED ISSUE #10: Clarify architecture for Mediaflux client
Team not ready to make a decision right now. One possibility:

- Client: generic, few public methods, parses xml response, makes error responses into exceptions
- Wrapper: multiple public methods, assembles XML, pulls out data from response
- Models: Decoupled from MF details

Or would just two layers be sufficient, with wrapper responsibilities moved either up or down?

### PR DESCRIPTION
**Pull request by mccalluc**
- Replaces #45 
- Fix #10

Without trying to prescribe how auth will work, or what the relational data or mediaflux data models are, or what will even be handled by mediaflux and what will be handled by postgres, or whether the API will be GraphQL or something simpler, this PR attempts to clarify the software architecture.

- UI and API will be independent: It is up to the developers to ensure that the functionality of the API matches the UI.
- We'll start a `MediafluxWrapper` class to contain all code related to Mediaflux. Eventually, credentials will probably be passed to the constructor.

### CODE REVIEW

File: app/models/mediaflux_wrapper.rb [hunk 1]
```diff
@@ -0,0 +1,10 @@
+# frozen_string_literal: true
+class MediafluxWrapper
+  # All calls to Mediaflux should be made through this class.
+  # TODO: Figure out authentication and authorization.
+  # TODO: Figure out what data Mediaflux and Postgres are responsible for.
+  # (Projects may eventually be handled by Postgres, but I need something for the example.)
```
Comment (jrgriffiniii) [inline app/models/mediaflux_wrapper.rb:6]: 👍

File: spec/controllers/api_v0_projects_controller_spec.rb [hunk 2]
```diff
@@ -0,0 +1,11 @@
+# frozen_string_literal: true
+require "rails_helper"
+
+RSpec.describe Api::V0::ProjectsController do
+  render_views
+
+  it "renders the index page" do
+    get :index, params: { format: :json }
+    expect(response.body).to include("[{")
```
Comment (jrgriffiniii) [inline spec/controllers/api_v0_projects_controller_spec.rb:9]: 👍

**Review by jrgriffiniii — APPROVED** [review]
